# https://travis-ci.org/pytorch/pytorch
# https://github.com/uber/pyro/blob/dev/.travis.yml
language: python

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

install:
    - pip install -e .[test]
    - pip freeze

jobs:
    fast_finish: true
    include:
        - stage: lint
          python: 2.7
          before_install: pip install -q flake8 nbstripout nbformat torch
          install:
          script: flake8
        - stage: unit test
          python: 2.7
          script: ./test/run_test.sh
        - python: 3.5
          script: ./test/run_test.sh
