# https://travis-ci.org/pytorch/pytorch
# https://github.com/uber/pyro/blob/dev/.travis.yml
language: python

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

install:
    # download and install PyTorch wheel
    - pip install --upgrade awscli
    - mkdir -p tmp
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        aws s3 --no-sign-request sync s3://pyro-ppl/ci tmp --exclude "*" --include "*-cp27-*";
      else
        aws s3 --no-sign-request sync s3://pyro-ppl/ci tmp --exclude "*" --include "*-cp35-*";
      fi
    - pip install tmp/*
    - rm -r tmp
    - pip install -e .[test]
    - pip freeze

jobs:
    fast_finish: true
    include:
        - stage: lint
          python: 2.7
          before_install: pip install flake8 nbstripout nbformat
          install:
          script: flake8
        - stage: unit test
          python: 2.7
          script: cd ./test/run_test.sh
        - python: 3.5
          script: cd ./test/run_test.sh
